services:
  - type: web
    name: kisan3
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node server.js
    publishDirectory: ./
    envVars:
      - key: NODE_ENV
        value: production
