services:
  - type: web
    name: kisan3
    runtime: node
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    publishDirectory: ./
    envVars:
      - key: NODE_ENV
        value: production
